name: '.NET code metrics'

on:
  workflow_dispatch:
  # TODO: disabled until a fix for https://github.com/dotnet/samples/issues/5640 exists
#  push:
##    branches: [ main ]
##    paths:
##      - '**.cs'
##      - '**.csproj'
#    paths-ignore:
#      # Ignore CODE_METRICS.md and README.md files
#      - '**.md'

env:
  TZ: America/Chicago

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      
      # Analyze repositories source metrics:
      # Create (or update) CODE_METRICS.md file.
      - name: .NET code metrics
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        # BROKEN: SEE HERE: https://github.com/dotnet/samples/issues/5640
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './src/mkmrk.Channels' }}

      - name: Lookaround
        run: ls -la
        
      - name: Show Changes
        run: |
          git status
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#packaging-workflow-data-as-artifacts
      - name: Upload Channels Code Metrics
        uses: actions/upload-artifact@v3
        with:
          name: channels-code-metrics
          path: 'src/mkmrk.Channels/CODE_METRICS.md'
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}