name: 'DocFX'

on:
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
  publish-docs:
    permissions:
      #contents: write
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json
      - name: Install dependencies
        run: dotnet restore
      
      # Build
      - name: Build
        working-directory: ./src/mkmrk.Channels/
        run: |
          dotnet build \
            --no-restore \
            --configuration Release \
            -consoleloggerparameters:"Summary;Verbosity=normal"

      # http://www.hiller.pro/mkmrk.Channels/
      # https://dotnet.github.io/docfx/index.html
      - run: dotnet tool update -g docfx
      #- run: docfx docs/docfx/docfx.json
      - run: docfx ./docfx.json
        working-directory: ./docs/docfx/

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: docs/docfx/_site
      - name: Upload GH Pages Artifact
        uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: docs/docfx/_site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

      - name: Write URL
        run: echo "Published URL: ${{ steps.report-test-results.outputs.page_url }}"