name: 'DocFX'

on:
  workflow_call:
    inputs:
      README_OUTPUT_PATH:
        required: true
        type: string

env:
  TZ: America/Chicago

jobs:
  publish-docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Retrieve Rendered Content
        uses: actions/download-artifact@v3
        with:
          name: Mermaid Render Results
          path: ${{ inputs.README_OUTPUT_PATH }}
        
      - name: Retrieve Generated Content
        uses: actions/download-artifact@v3
        with:
          name: test-generated-content
          path: ./docs/
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json
      - name: Install dependencies
        run: dotnet restore
      
      # Build
      - name: Build
        working-directory: ./src/mkmrk.Channels/
        run: |
          dotnet build \
            --no-restore \
            --configuration Release \
            -consoleloggerparameters:"Summary;Verbosity=normal"
      
      # Generate metrics
      - name: '.NET code metrics'
        id: dotnet-code-metrics
        #uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        # BROKEN: SEE HERE: https://github.com/dotnet/samples/issues/5640
        uses: erichiller/dotnet-samples-fork/github-actions/DotNet.GitHubAction@github-actions-summary-output-fix
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './src/mkmrk.Channels' }}
      - name: 'Move CODE_METRICS to docs'
        run: mv ./src/mkmrk.Channels/CODE_METRICS.md ./docs/stats/CODE_METRICS.md

      # http://www.hiller.pro/mkmrk.Channels/
      # https://dotnet.github.io/docfx/index.html
      - run: dotnet tool update -g docfx
      - run: docfx ./docfx.json
        working-directory: ./docs/
      #
      # https://github.com/actions/upload-artifact
      - name: Upload DocFX output
        uses: actions/upload-artifact@v3
        with:
          name: 'DocFX Output'
          path: ./docs
          retention-days: 30
      #
      # https://github.com/actions/upload-pages-artifact
      - name: Upload GH Pages Artifact
        uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: docs/_site
      #
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        #if: ${{ false }}
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

      - name: Write URL
        #if: ${{ false }}
        run: echo ${{ steps.deployment.outputs.page_url }}
