# https://learn.microsoft.com/en-us/dotnet/devops/dotnet-test-github-action
# 
name: Channel Tests

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # 
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json
          # Setup the Nuget feed
          # source-url: https://nuget.pkg.github.com/<owner>/index.json
          # TODO: I think if I set this, I don't have to see it EXPLICITLY in the below 
      - name: Get .NET information
        run: dotnet --info
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
#      - name: Lookaround
#        run: ls -la && ls -la ./src && ls -la ./src/mkmrk.Channels
#        # KILL
#      - name: Test at Root
#        run: dotnet test --no-restore --logger "console;verbosity=detailed"
#        # KILL
      - name: Test
        working-directory: ./test/mkmrk.Channels.Tests/
        run: dotnet test --logger "console;verbosity=normal" --logger "html;logfilename=testResults.html" --logger:"trx;LogFilePrefix=testResults" --filter 'FullyQualifiedName!~Latency'
        # dotnet test --logger "console;verbosity=detailed" --filter FullyQualifiedName\!~latency
#        run: dotnet test --no-restore --logger "console;verbosity=detailed" --diag ./diagnostics.log --results-directory ./TestResults
#        run: dotnet test --logger "console;verbosity=normal" --logger "html;logfilename=testResults.html" --filter '(FullyQualifiedName!~Latency)&(FullyQualifiedName!~AddingAndRemovingReadersShouldNeverError)'
        #    dotnet test --no-restore --logger "console;verbosity=detailed" --logger "html;logfilename=testResults.html" --diag ./diagnostics.log --filter FullyQualifiedName\!~latency
        #    dotnet test --logger "console;verbosity=detailed" --logger "html;logfilename=testResults.html;verbosity=detailed" --diag ./diagnostics.log --filter FullyQualifiedName\!~latency
        #    dotnet test --logger "console;verbosity=detailed" --logger "html;logfilename=testResults.html;verbosity=detailed" --filter '(FullyQualifiedName!~Latency)&(FullyQualifiedName!~AddingAndRemovingReadersShouldNeverError)'
        # --output ./TestResults 
        #run: dotnet test --no-restore --verbosity normal
        #run: dotnet test --no-restore --logger "console;verbosity=detailed" --filter "MarketDepth_SaveToDbTest" ./src/DataSource.Tests/DataSource.Tests.csproj
        # or
        # https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details
        # 
        # TODO: could add something like this to not do PostgreSQL tests:
        #   --filter Category!=Sql
        # TODO: eventually, it'd be nice to fully test, including setting up a PostgreSQL instance
        # URGENT: UNTESTED
      # URGENT: DISABLE THE BELOW
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#packaging-workflow-data-as-artifacts
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-results
          path: |
            ./test/mkmrk.Channels.Tests/TestResults/
            ./test/mkmrk.Channels.Tests/diagnostics.*
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
#
#
