name: 'Qodana'

on:
  workflow_dispatch:

env:
  TZ: America/Chicago

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Qodana config
        if: ${{ ! always() }}
        shell: pwsh
        run: |
          Set-Content -Path "./qodana.yaml" -Value (
            "exclude:" + "`n" +
            "  - name: All" + "`n" +
            "    paths:" + "`n" +
            "    - docs" + "`n" +
            "    - src/mkmrk.Channels/ChannelMux/DotnetRuntimeSourced"  + "`n" +
            "#    - benchmarks" + "`n"
          );
          Get-Content -Path "./qodana.yaml"
      #
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.1
        with:
          upload-result: true
          args: --print-problems
        
        
        # --linter jetbrains/qodana-dotnet
        # --print-problems
        # --report-dir ./qodana-reports
        # --results-dir ./qodana-results
        # --project-dir .
        # --save-report
        # Optional
        # --source-directory
        # --fail-threshold
        # --baseline
        
        # qodana scan --save-report
                        
      #
# 
# https://www.jetbrains.com/help/qodana/github.html
# https://www.jetbrains.com/help/qodana/qodana-yaml.html
# https://github.com/JetBrains/qodana-cli
# 
