name: 'ReSharper Inspection'

on:
  push:
    branches:
      - main
      - 'releases/*'
  #pull_request:
  #  types: [opened, reopened]
  workflow_dispatch:
  
jobs:
  inspect-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Annotate
        # You may pin to the exact commit or the version.
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          solution: ./mkmrk.Channels.sln

    #permissions:
    #  security-events: write
