name: 'ReSharper Inspection'

on:
  # TODO: RESTORE on.push
  # push:
  #   branches:
  #     - main
  #     - 'releases/*'
  # pull_request:
  #   types: [opened, reopened]
  workflow_dispatch:

env:
  TOOL_VERSION: 2023.2
  
jobs:
  inspect-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'preview'
      # One-time locally
      - name: Setup Jetbrains tool
        run: |
          dotnet new tool-manifest
          dotnet tool install JetBrains.ReSharper.GlobalTools
          # In the build script
          dotnet tool restore
      - name: run tool
        run: |
          dotnet tool run jb inspectcode ./mkmrk.Channels.sln \
             --Format=Text \
             --Format=Html \
             --Format=Xml \
             --Output=./results.txt
        #with:
        #  dotnet-version: ${{ inputs.dotnet-version }}
      # - name: Install ReSharper command line tools
      #   shell: bash
      #   run: dotnet tool install JetBrains.ReSharper.GlobalTools --global --version ${{ env.TOOL_VERSION }}
      # - name: Run inspection
      #   run: |
      #     jb inspectcode ./mkmrk.Channels.sln \
      #       --Format=Text \
      #       --Output=./results.txt
            
      #
      # https://www.jetbrains.com/help/resharper/InspectCode.html
      # https://github.com/JetBrains/ReSharper-InspectCode/blob/main/action.yml
      #- name: Annotate
        #uses: JetBrains/ReSharper-InspectCode@v0.3
        #with:
          #solution: ./mkmrk.Channels.sln
          #tool-version: 2023.2
          #output: './results.txt'
          #format: Text
          #format: 'Text;Html;Xml'
          #format: Html
          #format: Xml
          # LogFolder
          # swea: True  # (DEFAULT = use from settings file)
          # caches-home:
          # TODO: TRY --caches-home
          # verbosity: VERBOSE
          # debug: true
          # [INFO, HINT, SUGGESTION, WARNING, ERROR] # Suggestion is default
          # severity: 
      #
      #- name:
      #
      
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: inspection-results
          path: |
            ./results.txt
          # ./logs/

    #permissions:
    #  security-events: write

# https://www.jetbrains.com/help/resharper/InspectCode.html#command-line-parameters
# https://www.jetbrains.com/help/resharper/InspectCode.html#editorconfig
# --dumpIssuesTypes -it — use this option to dump all existing code inspections to the output. This option should be used separately from actual analysis, that is without the solution argument.

# -severity (-e) — by default, InspectCode only reports issues with the severity level Suggestion and higher. This parameter lets you change the minimal reported severity level to [INFO, HINT, SUGGESTION, WARNING, ERROR]. For example, -e=WARNING.


# TODO: (FUTURE) dotCover
#       https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html
# 

